// --------------------------------------------------------------------

var DTACK__GMAP__GIS_FEATURE_TYPE = "DTACK__GMAP__GIS_FEATURE_TYPE";
var DTACK__GMAP__GIS_FEATURE_TYPE__POINT = "1";
var DTACK__GMAP__GIS_FEATURE_TYPE__MULTI_SEGMENT_LINE = "2";
var DTACK__GMAP__GIS_FEATURE_TYPE__POLYLINE = "2";
var DTACK__GMAP__GIS_FEATURE_TYPE__IRREGULAR_AREA = "3";
var DTACK__GMAP__GIS_FEATURE_TYPE__POLYGON = "3";
var DTACK__GMAP__GIS_FEATURE_TYPE__RECTANGLE = "4";
var DTACK__GMAP__GIS_FEATURE_TYPE__CIRCLE = "5";
var DTACK__GMAP__GIS_FEATURE_TYPE__SINGLE_SEGMENT_LINE = "6";
var DTACK__GMAP__GIS_FEATURE_TYPE__TEXT = "7";

// --------------------------------------------------------------------
var DTACK__GMAP__KEYWORDS__PARENT_AUTOGUID = "DTACK__GMAP__KEYWORDS__PARENT_AUTOGUID";
var DTACK__GMAP__KEYWORDS__GIS_STYLE = "DTACK__GMAP__KEYWORDS__GIS_STYLE";

// --------------------------------------------------------------------
var DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_NOTHING = "DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_NOTHING";
var DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_MARKER = "DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_MARKER";
var DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_RECTANGLE = "DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_RECTANGLE";
var DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_CIRCLE = "DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_CIRCLE";
var DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_POLYLINE = "DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_POLYLINE";
var DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_POLYGON = "DTACK__GMAP__GIS__TRIGGER_EVENTS__EDITING_POLYGON";

// --------------------------------------------------------------------
